CREATE TABLE st_cs.charactor (
  ID VARCHAR(36) NOT NULL,
  NAME TEXT NOT NULL,
  CS_CLASS INT,
  CS_TYPE INT,
  CS_EAUDE INT,
  MEMO TEXT NOT NULL,
  PASSWORD TEXT,
  DISPLAY BOOLEAN NOT NULL,
  CREATE_DATE DATETIME NOT NULL,
  UPDATE_DATE DATETIME,
  PRIMARY KEY(ID)
);

CREATE TABLE st_cs.part (
  ID VARCHAR(36) NOT NULL,
  CID VARCHAR(36) NOT NULL,
  NAME TEXT NOT NULL,
  SHIHAI INT,
  JYUJYUN INT,
  DASAN INT,
  JYUNSHIN INT,
  OSHI INT,
  SASSHI INT,
  KOUI INT,
  AKUI INT,
  SORT INT NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE st_cs.item (
  ID VARCHAR(36) NOT NULL,
  CID VARCHAR(36) NOT NULL,
  NAME TEXT NOT NULL,
  MAIN INT,
  SUB INT,
  SORT INT NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE st_cs.skill (
  ID VARCHAR(36) NOT NULL,
  CID VARCHAR(36) NOT NULL,
  NAME TEXT NOT NULL,
  TIMING TEXT NOT NULL,
  COST INT,
  DETAIL TEXT NOT NULL,
  SORT INT NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE st_cs.relation (
  ID VARCHAR(36) NOT NULL,
  CID VARCHAR(36) NOT NULL,
  TARGET TEXT NOT NULL,
  NAME TEXT NOT NULL,
  UESHITA INT,
  SEMEUKE INT,
  SORT INT NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE st_cs.tension (
  ID VARCHAR(36) NOT NULL,
  CID VARCHAR(36) NOT NULL,
  NUM INT,
  STATUS INT NOT NULL,
  SORT INT NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE st_cs.tag (
  ID VARCHAR(36) NOT NULL,
  CID VARCHAR(36) NOT NULL,
  NAME TEXT NOT NULL,
  SORT INT NOT NULL,
  PRIMARY KEY(ID)
);
