CREATE TABLE charactor (
  ID VARCHAR(36) NOT NULL PRIMARY KEY,
  NAME TEXT NOT NULL,
  CS_CLASS INTEGER,
  CS_TYPE INTEGER,
  CS_EAUDE INTEGER,
  MEMO TEXT NOT NULL,
  PASSWORD TEXT,
  DISPLAY BOOLEAN NOT NULL,
  CREATE_DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELETE_DATE TIMESTAMP WITH TIME ZONE
);

CREATE TABLE part (
  ID VARCHAR(36) NOT NULL PRIMARY KEY,
  CID VARCHAR(36) NOT NULL,
  NAME TEXT NOT NULL,
  SHIHAI INTEGER,
  JYUJYUN INTEGER,
  DASAN INTEGER,
  JYUNSHIN INTEGER,
  OSHI INTEGER,
  SASSHI INTEGER,
  KOUI INTEGER,
  AKUI INTEGER,
  SORT INTEGER NOT NULL
);

CREATE TABLE item (
  ID VARCHAR(36) NOT NULL PRIMARY KEY,
  CID VARCHAR(36) NOT NULL,
  NAME TEXT NOT NULL,
  MAIN INTEGER,
  SUB INTEGER,
  SORT INTEGER NOT NULL
);

CREATE TABLE skill (
  ID VARCHAR(36) NOT NULL PRIMARY KEY,
  CID VARCHAR(36) NOT NULL,
  NAME TEXT NOT NULL,
  TIMING TEXT NOT NULL,
  COST INTEGER,
  DETAIL TEXT NOT NULL,
  SORT INTEGER NOT NULL
);

CREATE TABLE relation (
  ID VARCHAR(36) NOT NULL PRIMARY KEY,
  CID VARCHAR(36) NOT NULL,
  TARGET TEXT NOT NULL,
  NAME TEXT NOT NULL,
  UESHITA INTEGER,
  SEMEUKE INTEGER,
  SORT INTEGER NOT NULL
);

CREATE TABLE tension (
  ID VARCHAR(36) NOT NULL PRIMARY KEY,
  CID VARCHAR(36) NOT NULL,
  NUM INTEGER,
  STATUS INTEGER NOT NULL,
  SORT INTEGER NOT NULL
);

CREATE TABLE tag (
  ID VARCHAR(36) NOT NULL PRIMARY KEY,
  CID VARCHAR(36) NOT NULL,
  NAME TEXT NOT NULL,
  SORT INTEGER NOT NULL
);
